# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Developer's Log
tagline:          ''
description:      ''
url:              ndesh26.github.io
baseurl:

author:
  name:           'Nayan Deshmukh'
  url:            ndesh26.github.io
gems: [jekyll-paginate,jekyll-gist,redcarpet,kramdown, pygments]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ndesh26

future: true
