# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Searching Termination 
tagline:          ''
description:      ''
url:              ndesh26.github.io
baseurl:          /blog

author:
  name:           'Nayan Deshmukh'
  url:            ndesh26.github.io
gems: [jekyll-paginate,jekyll-gist,pygments.rb,redcarpet,kramdown]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ndesh26


